Ishvykin/feature
DungeonMaster1990/112ProxyMonitoringBackend pull request #43
Opened 2020-11-30 19:09 UTC by IVShvykin

2020-11-30 20:10 UTC, AlexanderStepchkov approved these changes

2020-11-30 20:10 UTC, AlexanderStepchkov commented on src/main/java/ru/vtb/monitoring/vtb112/db/vertica/repositories/implementations/SmRawdataMeasVerticaRepositoryImpl.java
> +        Integer offset = 0;
лучше использовать примитивный тип int, если не подразумевается возможность null

2020-11-30 20:10 UTC, AlexanderStepchkov commented on src/main/java/ru/vtb/monitoring/vtb112/db/vertica/repositories/implementations/SmRawdataMeasVerticaRepositoryImpl.java
> +                    limit 100
надо бы 100 вынести в переменную, а лучше в параметр

2020-11-30 20:10 UTC, AlexanderStepchkov commented on src/main/java/ru/vtb/monitoring/vtb112/db/vertica/repositories/implementations/SmRawdataMeasVerticaRepositoryImpl.java
> +            offset = offset + 100;
тут использовать переменную

2020-12-01 06:35 UTC, NMarkov88 requested changes

2020-12-01 06:35 UTC, NMarkov88 commented on src/main/java/ru/vtb/monitoring/vtb112/db/vertica/repositories/implementations/SmRawdataMeasVerticaRepositoryImpl.java
> +            ResultSet rs = stmt.executeQuery(newQuery);
ResultSet надо обернуть в try with resources

2020-12-01 09:43 UTC, merged